# Generated by Django 5.1.3 on 2024-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
