# Generated by Django 5.1.3 on 2024-11-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/pu.jpg', upload_to='profile_images/'),
        ),
    ]
