# Generated by Django 5.1.3 on 2024-12-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
